about/urls.py
from django.urls import path

from . import views

app_name = "about"

urlpatterns = [
    path("author/", views.AboutAuthorView.as_view(), name="author"),
    path("tech/", views.AboutTechView.as_view(), name="tech"),
]

posts/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("", views.index, name="index"),
    path("follow/", views.follow_index, name="follow_index"),
    path("group/<slug:slug>/", views.group_posts, name="group_posts"),
    path("new/", views.new_post, name="new_post"),
    path("<str:username>/", views.profile, name="profile"),
    path("<str:username>/<int:post_id>/", views.post_view, name="post"),
    path("<str:username>/<int:post_id>/edit/",
         views.post_edit, name="post_edit"),
    path("<str:username>/<int:post_id>/comment/",
         views.add_comment, name="add_comment"),
    path("<str:username>/follow/", views.profile_follow,
         name="profile_follow"),
    path("<str:username>/unfollow/", views.profile_unfollow,
         name="profile_unfollow"),
]

yatube/urls.py
from django.conf import settings
from django.conf.urls import handler404, handler500
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

handler404 = "posts.views.page_not_found"
handler500 = "posts.views.server_error"

urlpatterns = [
    path("auth/", include("users.urls")),
    path("auth/", include("django.contrib.auth.urls")),
    path("admin/", admin.site.urls),
    path("about/", include("about.urls", namespace="about")),
    path("", include("posts.urls")),
]


if settings.DEBUG:
    import debug_toolbar

    urlpatterns += (path("__debug__/", include(debug_toolbar.urls)),)
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )
    urlpatterns += static(
        settings.STATIC_URL, document_root=settings.STATIC_ROOT
    )

posts/models.py
from django.contrib.auth import get_user_model
from django.db import models
from pytils.translit import slugify

User = get_user_model()


class Post(models.Model):
    text = models.TextField(verbose_name="Запись",
                            help_text="Напишите что-нибудь здесь.")
    pub_date = models.DateTimeField("date published", auto_now_add=True,
                                    db_index=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE,
                               related_name="posts")
    group = models.ForeignKey("Group", verbose_name="Группа",
                              on_delete=models.SET_NULL, blank=True,
                              null=True, related_name="posts",
                              help_text="Выберите группу,"
                              " или оставьте поле пустым.")
    image = models.ImageField(verbose_name="Картинка",
                              upload_to="posts/", blank=True, null=True)

    class Meta:
        ordering = ["-pub_date"]

    def __str__(self):
        return self.text[:15]


class Group(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(unique=True)
    description = models.TextField()

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)[:100]
        super().save(*args, **kwargs)


class Comment(models.Model):
    post = models.ForeignKey(Post, verbose_name="Пост",
                             on_delete=models.CASCADE,
                             related_name="comments")
    author = models.ForeignKey(User, on_delete=models.CASCADE,
                               related_name="comments")
    text = models.TextField(verbose_name="Комментарий",
                            help_text="Оставьте комментарий.")
    created = models.DateTimeField(verbose_name="Дата публикации",
                                   auto_now_add=True)

    def __str__(self):
        return self.text[:15]


class Follow(models.Model):
    user = models.ForeignKey(User, verbose_name="Подписчик",
                             on_delete=models.CASCADE,
                             related_name="follower")
    author = models.ForeignKey(User, verbose_name="Автор",
                               on_delete=models.CASCADE,
                               related_name="following")

posts/forms.py
from django import forms

from .models import Comment, Post


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ["group", "text", "image"]
        error_messages = {
            "text": {
                "required": "Вы пытаетесь отправить пустую запись",
            },
        }


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ["text"]
        error_messages = {
            "text": {
                "required": "Вы пытаетесь отправить пустую запись",
            },
        }

posts/views.py
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse

from yatube.settings import PER_PAGE

from .forms import CommentForm, PostForm
from .models import Follow, Group, Post, User


def index(request):
    posts = Post.objects.all()

    paginator = Paginator(posts, PER_PAGE)
    page_number = request.GET.get("page")
    page = paginator.get_page(page_number)

    return render(
        request,
        "posts/index.html",
        {"page": page}
    )


def group_posts(request, slug):
    group = get_object_or_404(Group, slug=slug)
    posts = group.posts.all()

    paginator = Paginator(posts, PER_PAGE)
    page_number = request.GET.get("page")
    page = paginator.get_page(page_number)

    return render(request, "posts/group.html", {"group": group,
                                                "page": page})


@login_required
def new_post(request):
    new_post = True
    form = PostForm(
        request.POST or None,
        files=request.FILES or None
    )
    if form.is_valid():
        post = form.save(commit=False)
        post.author = request.user
        post.save()
        return redirect("index")

    return render(request, "posts/new.html",
                  {"new_post": new_post, "form": form})


def profile(request, username):
    author = get_object_or_404(User, username=username)
    posts = author.posts.all()

    paginator = Paginator(posts, PER_PAGE)
    page_number = request.GET.get("page")
    page = paginator.get_page(page_number)

    if request.user.is_authenticated:
        following = Follow.objects.filter(author=author,
                                          user=request.user).exists()
        return render(request, "posts/profile.html", {
            "author": author, "posts": posts,
            "page": page, "following": following
        })
    return render(
        request,
        "posts/profile.html",
        {"author": author, "posts": posts, "page": page}
    )


def post_view(request, username, post_id):
    post = get_object_or_404(Post, author__username=username,
                             pk=post_id)
    comments = post.comments.all()
    form = CommentForm()

    if request.user.is_authenticated:
        following = Follow.objects.filter(
            author=User.objects.get(username=username),
            user=request.user
        ).exists()
        return render(request, "posts/post.html",
                      {"author": post.author,
                       "posts": post.author.posts.all(),
                       "post": post,
                       "comments": comments,
                       "form": form,
                       "following": following})
    return render(request, "posts/post.html", {
        "author": post.author,
        "posts": post.author.posts.all(),
        "post": post,
        "comments": comments,
        "form": form,
    })


@login_required
def post_edit(request, username, post_id):
    new_post = False
    url = reverse("post", kwargs={"username": username,
                                  "post_id": post_id})
    post = get_object_or_404(Post, author__username=username, pk=post_id)
    if request.user != post.author:
        return redirect(url)

    form = PostForm(
        request.POST or None,
        files=request.FILES or None,
        instance=post
    )
    if form.is_valid():
        form.save()
        return redirect(url)
    return render(request, "posts/new.html", {"username": username,
                                              "post_id": post_id,
                                              "new_post": new_post,
                                              "post": post,
                                              "form": form})


@login_required
def add_comment(request, username, post_id):
    url = reverse("post", kwargs={"username": username,
                                  "post_id": post_id})
    post = get_object_or_404(Post, author__username=username, pk=post_id)
    comments = post.comments.all()

    form = CommentForm(
        request.POST or None
    )

    following = Follow.objects.filter(
        author=User.objects.get(username=username),
        user=request.user
    ).exists()

    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()
        return redirect(url)

    return render(request, "posts/post.html", {
        "author": post.author,
        "posts": post.author.posts.all(),
        "post": post,
        "form": form,
        "comments": comments,
        "following": following
    })


@login_required
def follow_index(request):
    posts = Post.objects.filter(author__following__user=request.user)

    paginator = Paginator(posts, PER_PAGE)
    page_number = request.GET.get("page")
    page = paginator.get_page(page_number)
    return render(request, "posts/follow.html",
                  {"page": page, "paginator": paginator})


@login_required
def profile_follow(request, username):
    author = get_object_or_404(User, username=username)
    if request.user != author:
        is_following = Follow.objects.filter(
            user=request.user, author=author
        ).exists()
        if not is_following:
            Follow.objects.create(user=request.user, author=author)
    return redirect(reverse("follow_index"))


@login_required
def profile_unfollow(request, username):
    author = get_object_or_404(User, username=username)

    Follow.objects.filter(user=request.user,
                          author=author).delete()
    return redirect(reverse("follow_index"))


def page_not_found(request, exception):
    return render(
        request,
        "misc/404.html",
        {"path": request.path},
        status=404
    )


def server_error(request):
    return render(request, "misc/500.html", status=500)

posts/templates/posts/base.html
<!doctype html>
<html>

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <title>{% block title %}The Last Social Media You'll Ever Need{% endblock %} | Yatube</title>
  <!-- Загрузка статики -->
  {% load static %}
  <link rel="stylesheet" href="{% static 'bootstrap/dist/css/bootstrap.min.css' %}">
  <script src="{% static 'jquery/dist/jquery.min.js' %}"></script>
  <script src="{% static 'bootstrap/dist/js/bootstrap.min.js' %}"></script>
</head>

<body>
  {% include "posts/nav.html" %}
  <main>
    <div class="container">
      <h1>{% block header %}The Last Social Media You'll Ever Need{% endblock %}</h1>
      <p>
        {% block description %}{% endblock %}
      </p>
      {% block content %}
      <!-- Содержимое страницы -->
      {% endblock %}
    </div>
  </main>
  {% include "posts/footer.html" %}
</body>

</html>

posts/templates/posts/card_author.html
<div class="col-md-3 mb-3 mt-1">
  <div class="card">
    <div class="card-body">
      <div class="h2">
        <!-- Имя автора -->
        {{ author.get_full_name }}
      </div>
      <div class="h3 text-muted">
        <!-- username автора -->
        {{ author.username }}
      </div>
    </div>
    <ul class="list-group list-group-flush">
      <li class="list-group-item">
        <div class="h6 text-muted">
          Подписчиков: {{ author.following.count }} <br />
          Подписан: {{ author.follower.count }}
        </div>
      </li>
      <li class="list-group-item">
        <div class="h6 text-muted">
          <!-- Количество записей -->
          Записей {{ posts.count }}
        </div>
      </li>
    </ul>
    <li class="list-group-item">
      {% if following %}
      <a class="btn btn-lg btn-light" href="{% url 'profile_unfollow' author.username %}" role="button">
        Отписаться
      </a>
      {% else %}
      <a class="btn btn-lg btn-primary" href="{% url 'profile_follow' author.username %}" role="button">
        Подписаться
      </a>
      {% endif %}
    </li>
  </div>
</div>

posts/templates/posts/comments.html
<!-- Форма добавления комментария -->
{% load user_filters %}

{% if user.is_authenticated %}
{% if form %}
<div class="card my-4">
  <form method="post" action="{% url 'add_comment' username=author.username post_id=post.pk %}">
    {% csrf_token %}
    <h5 class="card-header">Добавить комментарий:</h5>
    <div class="card-body">
      <div class="form-group">
        {{ form.text|addclass:"form-control" }}
      </div>
      <button type="submit" class="btn btn-primary">Отправить</button>
    </div>
  </form>
</div>
{% endif %}
{% endif %}

<!-- Комментарии -->
{% for item in comments %}
<div class="media card mb-4">
  <div class="media-body card-body">
    <h5 class="mt-0">
      <a href="{% url 'profile' item.author.username %}" name="comment_{{ item.id }}">
        {{ item.author.username }}
      </a>
    </h5>
    <p style="font-size:14px;">{{ item.text | linebreaksbr }}</p>
  </div>
</div>
{% endfor %}

posts/templates/posts/follow.html
{% extends "posts/base.html" %}
{% block title %} Последние обновления {% endblock %}

{% block content %}
{% load cache %}
{% cache 20 follow_page %}
<div class="container">

  {% include "posts/menu.html" with follow=True %}

  <h1> Последние новости у авторов, за которыми вы следите</h1>
  <!-- Вывод ленты записей -->
  {% for post in page %}

  {% include "posts/post_item.html" with post=post %}
  {% endfor %}
</div>
{% endcache %}
<!-- Вывод паджинатора -->
{% if page.has_other_pages %}
{% include "posts/paginator.html" with items=page paginator=paginator%}
{% endif %}

{% endblock %}

posts/templates/posts/footer.html
<footer class="pt-4 my-md-5 pt-md-5 border-top">
  <p class="m-0 text-dark text-center ">
    <a href="{% url 'about:author' %}">Об авторе</a>
  </p>
  <p class="m-0 text-dark text-center ">
    <a href="{% url 'about:tech' %}">Технологии</a>
  </p>
  <p class="m-0 text-dark text-center ">Социальная сеть <span style="color:red">Ya</span>tube © {{ year }}, все права защищены.</p>
</footer>

posts/templates/posts/group.html
{% extends "posts/base.html" %}
{% block title %}Записи сообщества {{ group }}{% endblock %}
{% block header %}{{ group }}{% endblock %}
{% block description %}{{ group.description }}{% endblock %}
{% block content %}

{% for post in page %}
{% include "posts/post_item.html" %}
{% endfor %}

<!-- Вывод паджинатора -->
{% if page.has_other_pages %}
{% include "posts/paginator.html" with items=page %}
{% endif %}

{% endblock %}

posts/templates/posts/index.html
{% extends "posts/base.html" %}
{% block title %} Последние обновления {% endblock %}

{% block content %}
{% load cache %}
{% cache 20 index_page %}
<div class="container">

  {% include "posts/menu.html" with index=True %}

  <h1> Последние обновления на сайте</h1>
  <!-- Вывод ленты записей -->
  {% for post in page %}

  {% include "posts/post_item.html" with post=post %}
  {% endfor %}
</div>
{% endcache %}
<!-- Вывод паджинатора -->
{% if page.has_other_pages %}
{% include "posts/paginator.html" with items=page %}
{% endif %}

{% endblock %}

posts/templates/posts/menu.html
{% if user.is_authenticated %}
<div class="row">
  <ul class="nav nav-tabs">
    <li class="nav-item">
      <a class="nav-link {% if index %}active{% endif %}" href="{% url 'index' %}">
        Все авторы
      </a>
    </li>
    <li class="nav-item">
      <a class="nav-link {% if follow %}active{% endif %}" href="/follow">
        Избранные авторы
      </a>
    </li>
  </ul>
</div>
{% endif %}

posts/templates/posts/nav.html
<nav class="navbar navbar-light" style="background-color: #e3f2fd;">
  <a class="navbar-brand" href="{% url 'index' %}"><span style="color:red">Ya</span>tube</a>
  <nav class="my-2 my-md-0 mr-md-3">
    {% if user.is_authenticated %}
    Пользователь: {{ user.username }}.
    <a class="p-2 text-dark" href="{% url 'new_post' %}">Новая запись</a>
    <a class="p-2 text-dark" href="{% url 'password_change' %}">Изменить пароль</a>
    <a class="p-2 text-dark" href="{% url 'logout' %}">Выйти</a>
    {% else %}
    <a class="p-2 text-dark" href="{% url 'login' %}">Войти</a> |
    <a class="p-2 text-dark" href="{% url 'signup' %}">Регистрация</a>
    {% endif %}
  </nav>
</nav>

posts/templates/posts/new.html
{% extends "posts/base.html" %}
{% block title %}Редактирование записи{% endblock %}
{% block header %}{% endblock %}
{% block description %}{% endblock %}
{% block content %}
{% load user_filters %}

<div class="row justify-content-center">
  <div class="col-md-8 p-5">
    <div class="card">
      <div class="card-header">
        {% if new_post %}
        Добавить запись
        {% else %}
        Редактировать запись
        {% endif %}
      </div>

      <div class="card-body">

        {% for error in form.errors.values %}
        <div class="alert alert-danger" role="alert">
          {{ error|escape }}
        </div>
        {% endfor %}

        <form method="post" enctype="multipart/form-data" action="{% if new_post %}{% url 'new_post' %}{% else %}{% url 'post_edit' username post_id %}{% endif %}">
          {% csrf_token %}

          {% for field in form %}
          <div class="form-group row" aria-required={% if field.field.required %}"true"{% else %}"false"{% endif %}>
            <label for="{{ field.id_for_label }}" class="col-md-4 col-form-label text-md-right">{{ field.label }}{% if field.field.required %}<span class="required">*</span>{% endif %}</label>
            <div class="col-md-6">

              {{ field|addclass:"form-control" }}

              {% if field.help_text %}
              <small id="{{ field.id_for_label }}-help" class="form-text text-muted">{{ field.help_text|safe }}</small>
              {% endif %}
            </div>
          </div>
          {% endfor %}

          <div class="col-md-6 offset-md-4">
            <button type="submit" class="btn btn-primary">
              {% if new_post %}
              Добавить
              {% else %}
              Сохранить
              {% endif %}
            </button>
          </div>
        </form>
      </div> <!-- card body -->
    </div> <!-- card -->
  </div> <!-- col -->
</div> <!-- row -->

{% endblock %}

posts/templates/posts/paginator.html
{% if page.has_other_pages %}
<nav>
  <ul class="pagination">
    {% if page.has_previous %}
    <li class="page-item">
      <a class="page-link" href="?page={{ page.previous_page_number }}">&laquo; Предыдущая</a>
    </li>
    {% endif %}
    {% for i in page.paginator.page_range %}
    {% if page.number == i %}
    <li class="page-item active">
      <span class="page-link">{{ i }}
        <span class="sr-only">(текущая)</span>
      </span>
    </li>
    {% else %}
    <li class="page-item">
      <a class="page-link" href="?page={{ i }}">{{ i }}</a>
    </li>
    {% endif %}
    {% endfor %}
    {% if page.has_next %}
    <li class="page-item">
      <a class="page-link" href="?page={{ page.next_page_number }}">&raquo; Следующая</a>
    </li>
    {% else %}
    <li class="page-item disabled">
      <span class="page-link">Следующая &raquo;</span>
    </li>
    {% endif %}
  </ul>
</nav>
{% endif %}

posts/templates/posts/post.html
{% extends "posts/base.html" %}
{% block content %}

<main role="main" class="container">
  <div class="row">
    {% include "posts/card_author.html" %}
    <div class="col-md-9">
      <!-- Пост -->
      {% include "posts/post_item.html" %}
      {% include "posts/comments.html" %}
    </div>
  </div>
</main>
{% endblock %}

posts/templates/posts/post_item.html
<div class="card mb-3 mt-1 shadow-sm">

  <!-- Отображение картинки -->
  {% load thumbnail %}
  {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
  <img class="card-img" src="{{ im.url }}" />
  {% endthumbnail %}
  <!-- Отображение текста поста -->
  <div class="card-body">
    <p class="card-text">
      <!-- Ссылка на автора через @ -->
      <a name="post_{{ post.id }}" href="{% url 'profile' post.author.username %}">
        <strong class="d-block text-gray-dark">@{{ post.author }}</strong>
      </a>
      {{ post.text|linebreaksbr }}
    </p>

    <!-- Если пост относится к какому-нибудь сообществу, то отобразим ссылку на него через # -->
    {% if post.group %}
    <a class="card-link muted" href="{% url 'group_posts' post.group.slug %}">
      <strong class="d-block text-gray-dark">#{{ post.group.title }}</strong>
    </a>
    {% endif %}

    <!-- Отображение ссылки на комментарии -->
    <div class="d-flex justify-content-between align-items-center">
      <div class="btn-group">
        {% if post.comments.exists %}
        <div class="btn btn-sm text-muted">
          Комментариев: {{ post.comments.count }}
        </div>
        {% endif %}
        <a class="btn btn-sm text-muted" href="{% url 'add_comment' post.author.username post.id %}" role="button">
          Добавить комментарий
        </a>

        <!-- Ссылка на редактирование поста для автора -->
        {% if user == post.author %}
        <a class="btn btn-sm text-muted" href="{% url 'post_edit' post.author.username post.id %}" role="button">
          Редактировать
        </a>
        {% endif %}
      </div>

      <!-- Дата публикации поста -->
      <small class="text-muted">{{ post.pub_date }}</small>
    </div>
  </div>
</div>

posts/templates/posts/profile.html
{% extends "posts/base.html" %}
{% block content %}

<main role="main" class="container">
  <div class="row">
    {% include "posts/card_author.html" %}

    <div class="col-md-9">
      {% for post in page %}
      <!-- Начало блока с отдельным постом -->
      {% include "posts/post_item.html" %}
      <!-- Конец блока с отдельным постом -->
      {% endfor %}

      <!-- Вывод паджинатора -->
      {% if page.has_other_pages %}
      {% include "posts/paginator.html" with items=page %}
      {% endif %}
    </div>
  </div>
</main>

{% endblock %}